import Head from "next/head";

export default function Home() {
  let name: string = "Hoà Ký";
  let isLoading: boolean;

  isLoading = false;

  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Home page {name}</h1>
    </>
  );
}
