import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home() {
  let name: string = "Hoà Ký";

  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="/css/home.css" />
      </Head>
      <h1 className={styles.main}>Home page {name}</h1>
    </>
  );
}
